### PR TITLE
decreaseTime functionality

### PR DESCRIPTION
**Pull request by kishyassin**
This pull request introduces a new feature to decrease time in the `FoundationsService` and updates the `Form` component to support this functionality. The main changes include adding a new method to the service and modifying the form to handle the new decrease time action.

### New Feature Implementation:

* [`common/service.ts`](diffhunk://#diff-9ebabbbb01e70b8008602a8adaefca10d73382eb2245eaa276d9aff6c30e65e1R27-R31): Added a new method `decreaseTime` to the `FoundationsService` to implement the functionality to decrease time.

### Form Component Updates:

* [`frontend/Form.tsx`](diffhunk://#diff-7bb3ed5070b87a58e5a9b64e9550c62dfe3606fd5d3d48af51bc624e4a29e7d2L4-R11): Refactored the `Form` component to improve code readability by adjusting the formatting of the `onSubmit` handler.
* [`frontend/Form.tsx`](diffhunk://#diff-7bb3ed5070b87a58e5a9b64e9550c62dfe3606fd5d3d48af51bc624e4a29e7d2R23-R36): Added a new handler `onDecrease` to handle the decrease time action.
* [`frontend/Form.tsx`](diffhunk://#diff-7bb3ed5070b87a58e5a9b64e9550c62dfe3606fd5d3d48af51bc624e4a29e7d2R58-R60): Added a new button to trigger the `onDecrease` handler, allowing users to decrease time.

### CODE REVIEW

**Comment by m1dugh** [comment]
Hello, I am currently working on a rework of the project. It is gonna be a full refacto with proper typrescript and migration to deno. If you want to work on it, feel free to look at the branch called `v3-refacto`, which is currently almost empty.
Regarding decrease time, it is not possible to decrease time on the rosetta stone backend, so it won't be possible.

**Comment by kishyassin** [comment]
Hi @m1dugh ,
Thank you for your reply
that sounds great, I woukd be happy to help on refactoring the project,
I'll keep following

**Comment by m1dugh** [comment]
The rework is almost done, you can look at it on the `v3-refacto` branch, it includes:
- [x] full rewriting of the codebase
- [x] compatibility with mozilla
- [x] packaging made by deno
- [x] frontend in react js

Here are the remaining things to do:
- [ ] fix the frontend so it looks like something
- [ ] fix the mozilla xpi packaging to allow proper mozilla packaging
- [ ] add github actions to package for both firefox and chromium
- [ ] add contributing documentation
- [ ] add readme for user documentation

**Comment by m1dugh** [comment]
Hello @kishyassin,
I have finished the refacto of the code, and merged it into master, I'm gonna close this pr, feel free to open another one if your want to contribute on the project.

**Comment by kishyassin** [comment]
Thank you @m1dugh 
I see you have done it well
great job

**Pull request closed without merging**
